function [ Xdata_events_train,Ydata_events_train,...
          Xdata_events_test,Ydata_events_test,...
          events_flag_train,events_flag_test,...
          Xdata_normal_train,Ydata_normal_train,...
            Xdata_normal_test,Ydata_normal_test] = load_data(FileNameEvents,FileNameNormal)
%	加载训练数据和测试数据
%   返回
    [Xdata_events_train,Ydata_events_train,...
     Xdata_events_test,Ydata_events_test,...
     events_flag_train,events_flag_test,...
     Xdata_normal_train,Ydata_normal_train,...
            Xdata_normal_test,Ydata_normal_test] = create_dataset(FileNameNormal,FileNameEvents);

end

